name: Deploy staging and production to Firebase App Distribution

on:
  # Trigger the workflow on push action in develop branch.
  # So it will trigger when the PR of the feature branch was merged.
  push:
    branches:
      - develop

jobs:
  deploy_staging_and_production_to_firebase_app_distribution:
    name: Deploy staging and production to Firebase App Distribution
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Bangkok

      - name: Checkout source code
        uses: actions/checkout@v2.3.2

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up google-services.json files
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          GOOGLE_SERVICES_JSON_STAGING: ${{ secrets.GOOGLE_SERVICES_JSON_STAGING }}
        run: |
          mkdir -p app/src/production
          echo $GOOGLE_SERVICES_JSON > app/src/production/google-services.json
          mkdir -p app/src/staging
          echo $GOOGLE_SERVICES_JSON_STAGING > app/src/staging/google-services.json

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Archive Detekt reports
        uses: actions/upload-artifact@v2
        with:
          name: DetektReports
          path: build/reports/detekt/

      - name: Run unit tests with Kover
        run: ./gradlew koverHtmlReport

      - name: Archive code coverage reports
        uses: actions/upload-artifact@v2
        with:
          name: CodeCoverageReports
          path: app/build/reports/kover/

      - name: Build staging APK
        run: ./gradlew assembleStagingDebug

      - name: Deploy staging to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID_STAGING}}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app/build/outputs/apk/staging/debug/app-staging-debug.apk

      - name: Build production APK
        run: ./gradlew assembleProductionDebug

      - name: Deploy production to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID_PRODUCTION}}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app/build/outputs/apk/production/debug/app-production-debug.apk
