name: Review pull request

on:
  pull_request:
    types: [ opened, edited, reopened, synchronize ]

jobs:
  review_pull_request:
    name: Review pull request
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout source code
        uses: actions/checkout@v2.3.2

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Run Detekt and generate Detekt reports
      - name: Run Detekt
        run: ./gradlew detekt

      # Run Android Lint and generate Lint reports
      - name: Run Android Lint
        run: ./gradlew lint

      # Run unit tests and Jacoco for code coverage
      - name: Run unit tests and Jacoco
        run: ./gradlew jacocoTestReport

      # Set up Ruby gems and Bundle for executing danger-ruby
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Bundle and check environment versions
        run: |
          echo 'Install Bundle'
          bundle config path vendor/bundle
          bundle install
          echo 'Check environment setup versions'
          ruby --version
          gem --version
          bundler --version

      - name: Run Danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec danger
