definitions:
  configure_environment: &configure_environment
    instance_type: linux_x2
    max_build_duration: 60
    cache:
      cache_paths:
        - $HOME/.gradle/caches
  scripts:
    - &detekt
      name: Run detekt static code analysis
      script: ./gradlew detekt
      ignore_failure: true
    - &unit-test
      name: Run unit tests and generate coverage report using Kover
      script: ./gradlew koverMergedReport
  artifacts: &artifacts
    artifacts:
      - app/build/reports/jacoco/jacocoTestReport/
workflows:
  unit-test-on-pr:
    name: Unit test on PR
    <<: *configure_environment
    triggering:
      events:
        - pull_request
      cancel_previous_builds: true
    scripts:
      - *detekt
      - *unit-test
    <<: *artifacts

  unit-test-on-push:
    name: Unit test on push
    <<: *configure_environment
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
        - pattern: develop
          include: false
        - pattern: 'release/**'
          include: false
        - pattern: 'hotfix/**'
          include: false
        - pattern: master
          include: false
      cancel_previous_builds: true
    scripts:
      - *detekt
      - *unit-test
    <<: *artifacts
