definitions:
  configure_environment: &configure_environment
    instance_type: mac_mini_m1
    max_build_duration: 30
    cache:
      cache_paths:
        - $HOME/.gradle/caches
  scripts:
    - &detekt_on_template_compose
      name: Run detekt on template-compose
      working_directory: ./template-compose
      script: ./gradlew detekt
    - &detekt_on_template_xml
      name: Run detekt on template-xml
      working_directory: ./template-xml
      script: ./gradlew detekt
    - &unit_test_on_template_compose
      name: Run unit tests on template-compose
      working_directory: ./template-compose
      script: ./gradlew koverMergedReport
    - &unit_test_on_template_xml
      name: Run unit tests on template-xml
      working_directory: ./template-xml
      script: ./gradlew koverMergedReport
  artifacts:
    - &artifacts_template_compose template-compose/build/reports/kover/merged/
    - &artifacts_template_xml template-xml/build/reports/kover/merged/
workflows:
  unit-test-on-pr-for-template-compose:
    name: Unit test on PR for template-compose
    <<: *configure_environment
    triggering:
      events:
        # run when a pull request is opened or updated
        - pull_request
      branch_patterns:
        # review changes BEFORE they’re merged into any branches
        - pattern: '*'
          source: false
        # review changes AFTER they have been merged into develop branch
        - pattern: 'develop'
        # review changes AFTER they have been merged into main branch
        - pattern: 'main'
      cancel_previous_builds: true
    scripts:
      - *detekt_on_template_compose
      - *unit_test_on_template_compose
    artifacts:
      - *artifacts_template_compose

  unit-test-on-pr-for-template-xml:
    name: Unit test on PR for template-xml
    <<: *configure_environment
    triggering:
      events:
        # run when a pull request is opened or updated
        - pull_request
      branch_patterns:
        # review changes BEFORE they’re merged into any branches
        - pattern: '*'
          source: false
        # review changes AFTER they have been merged into develop branch
        - pattern: 'develop'
        # review changes AFTER they have been merged into main branch
        - pattern: 'main'
      cancel_previous_builds: true
    scripts:
      - *detekt_on_template_xml
      - *unit_test_on_template_xml
    artifacts:
      - *artifacts_template_xml
