definitions:
  configure_environment: &configure_environment
    instance_type: mac_mini_m1
    max_build_duration: 30
    cache:
      cache_paths:
        - $HOME/.gradle/caches
  scripts:
    - &detekt_on_template_compose
      name: Run detekt on template-compose
      working_directory: ./template-compose
      script: ./gradlew detekt
    - &detekt_on_template_xml
      name: Run detekt on template-xml
      working_directory: ./template-xml
      script: ./gradlew detekt
    - &unit_test_on_template_compose
      name: Run unit tests on template-compose
      working_directory: ./template-compose
      script: ./gradlew koverMergedReport
    - &unit_test_on_template_xml
      name: Run unit tests on template-xml
      working_directory: ./template-xml
      script: ./gradlew koverMergedReport
  artifacts:
    - &artifacts_template_compose template-compose/build/reports/kover/merged/
    - &artifacts_template_xml template-xml/build/reports/kover/merged/
    - &artifacts_staging_apk template-compose/app/build/outputs/apk/staging/debug/app-staging-debug.apk
    - &artifacts_production_apk template-compose/app/build/outputs/apk/production/debug/app-production-debug.apk
workflows:
  unit-test-on-pr-for-template-compose:
    name: Unit test on PR for template-compose
    <<: *configure_environment
    triggering:
      events:
        # run when a pull request is opened or updated
        - pull_request
      branch_patterns:
        # review changes BEFORE they’re merged into any branches
        - pattern: '*'
          source: false
        # will not run on develop branch as it is already covered by build-and-deploy-template-compose-staging
        - pattern: 'develop'
          include: false
        # # will not run on main branch as it is already covered by build-and-deploy-template-compose-production
        - pattern: 'main'
          include: false
      cancel_previous_builds: true
    scripts:
      - *detekt_on_template_compose
      - *unit_test_on_template_compose
    artifacts:
      - *artifacts_template_compose

  unit-test-on-pr-for-template-xml:
    name: Unit test on PR for template-xml
    <<: *configure_environment
    triggering:
      events:
        # run when a pull request is opened or updated
        - pull_request
      branch_patterns:
        # review changes BEFORE they’re merged into any branches
        - pattern: '*'
          source: false
        # will not run on develop branch as it is already covered by build-and-deploy-template-compose-staging
        - pattern: 'develop'
          include: false
        # # will not run on main branch as it is already covered by build-and-deploy-template-compose-production
        - pattern: 'main'
          include: false
      cancel_previous_builds: true
    scripts:
      - *detekt_on_template_xml
      - *unit_test_on_template_xml
    artifacts:
      - *artifacts_template_xml

  build-and-deploy-template-compose-staging:
    name: Build and deploy template-compose staging to Firebase App Distribution
    <<: *configure_environment
    environment:
      groups:
        - firebase_credentials
        - build_configure
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: develop
    scripts:
      - *detekt_on_template_compose
      - *unit_test_on_template_compose
      - name: Build APK for staging
        working_directory: ./template-compose
        script: |
          ./gradlew assembleStagingDebug -PversionCode=$BUILD_NUMBER
    artifacts:
      - *artifacts_template_compose
      - *artifacts_staging_apk
    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT_CREDENTIALS
        android:
          app_id: 1:215362241811:android:51e902760fcff1243446e6
          groups:
            - android-chapter
          artifact_type: 'apk'

  build-and-deploy-template-compose-production:
    name: Build and deploy template-compose production to Firebase App Distribution
    <<: *configure_environment
    environment:
      groups:
        - firebase_credentials
        - build_configure
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - *detekt_on_template_compose
      - *unit_test_on_template_compose
      - name: Build APK for production
        working_directory: ./template-compose
        script: |
          ./gradlew assembleProductionDebug -PversionCode=$BUILD_NUMBER
    artifacts:
      - *artifacts_template_compose
      - *artifacts_production_apk
    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT_CREDENTIALS
        android:
          app_id: 1:215362241811:android:f4f209cd4a5f3d5b3446e6
          groups:
            - android-chapter
          artifact_type: 'apk'
