name: Automatically review code

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  review_code:
    name: Run Danger 
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout source code
        uses: actions/checkout@v2.3.2

      - name: Load Gradle cached
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Danger
        uses: danger/kotlin@1.0.0-beta.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}