name: Draft new release

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  draft_new_release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Kscript
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          source version.properties
          sdk install kotlin $kotlinVersion
          sdk install kscript $kscriptVersion
          echo $PATH >> $GITHUB_PATH

      - name: Get version from the latest commit message
        working-directory: scripts
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          VERSION=$(kscript get_version.kts "$COMMIT_MESSAGE")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Draft release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-drafter-config.yml
          version: ${{ env.VERSION }}
