name: Lint and Test

# Choose the branch or branches you want to run this workflow
on: push
jobs:
  lint_and_test:
    name: Static code analysis and unit test
    runs-on: macOS-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/checkout@v2.3.2

      - name: Load Gradle cached
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Archive Detekt report
        uses: actions/upload-artifact@v2
        with:
          name: detekt-report
          path: build/reports/detekt/

      - name: Run Unit Tests & Jacoco
        run: ./gradlew jacocoTestReport

      # Archive Unit test & code coverage report
      - name: Archive Code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: |
            app/build/reports/jacoco/jacocoTestReport/
            data/build/reports/jacoco/jacocoTestReport/
