name: Publish docs to Wiki

on:
  push:
    paths:
      - .github/wiki/**
    branches:
      - main
      - bug/455-fix-publish-wiki-workflow

jobs:
  publish_docs_to_wiki:
    name: Publish docs to Wiki
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout the repository
        uses: actions/checkout@v2.3.2
        with:
          ref: ${{ github.head_ref }}

      - name: Publish Github Wiki
        uses: nimblehq/publish-github-wiki-action@v1.0
        with:
          user_name: team-nimblehq
          user_email: dev@nimblehq.co
          user_access_token: ${{ secrets.WIKI_ACTION_TOKEN }}
