name: Publish docs to Wiki

on:
  push:
    paths:
      - docs/**
    branches:
      - main

jobs:
  publish_docs_to_wiki:
    name: Publish docs to Wiki
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Publish Github Wiki
        uses: nimblehq/publish-github-wiki-action@v1.0
        with:
          user_name: team-nimblehq
          user_email: dev@nimblehq.co
          user_access_token: ${{ secrets.WIKI_ACTION_TOKEN }}
