name: Create Draft Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write  # for release-drafter/release-drafter to create a github release
      pull-requests: write  # for release-drafter/release-drafter to add label to PR
    runs-on: ubuntu-latest
    steps:
      # TODO: determine the next version before the following step and pass it as an input.
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yml
          disable-autolabeler: true
          # version: here goes the next version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
