name: Verify newproject script

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ develop ]

jobs:
  verify_newproject_script:
    name: Verify newproject script
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Checkout source code
        uses: actions/checkout@v2.3.2

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Kscript
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          source version.properties
          sdk install kotlin $kotlinVersion
          sdk install kscript $kscriptVersion
          echo $PATH >> $GITHUB_PATH

      - name: Verify generating new project from template
        working-directory: scripts
        run: kscript new_project.kts package-name=co.myproject.example app-name="My Project"
